apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-watcher-script
data:
  secret-watcher.sh: |
    #!/bin/bash

    SECRET_FILE="/etc/secrets/my-secret"  # Update with your secret file path

    echo "Monitoring $SECRET_FILE for changes..."

    # Ensure inotifywait is available
    if ! command -v inotifywait &> /dev/null; then
      echo "inotifywait could not be found. Install inotify-tools package."
      exit 1
    fi

    # Monitor changes to the secret file
    while true; do
      inotifywait -e modify,create,delete "$SECRET_FILE" && {
        echo "$(date): Secret file changed. Reloading..."
        NEW_SECRET=$(cat "$SECRET_FILE")
        echo "New Secret Value: $NEW_SECRET"
        # Add your application's reload logic here (e.g., restart services, update config)
      }
    done
